// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payloads/schemas/GoFGame.proto

package de.gameoflife.payloads;

public final class GoFGame {
  private GoFGame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Game)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string gameName = 1;</code>
     */
    java.lang.String getGameName();
    /**
     * <code>string gameName = 1;</code>
     */
    com.google.protobuf.ByteString
        getGameNameBytes();

    /**
     * <code>string creationDate = 2;</code>
     */
    java.lang.String getCreationDate();
    /**
     * <code>string creationDate = 2;</code>
     */
    com.google.protobuf.ByteString
        getCreationDateBytes();

    /**
     * <code>string lastModifiedDate = 3;</code>
     */
    java.lang.String getLastModifiedDate();
    /**
     * <code>string lastModifiedDate = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastModifiedDateBytes();

    /**
     * <code>int32 userID = 4;</code>
     */
    int getUserID();

    /**
     * <code>int32 gameID = 5;</code>
     */
    int getGameID();

    /**
     * <code>bool borderOverflow = 6;</code>
     */
    boolean getBorderOverflow();

    /**
     * <code>bool historyAvailable = 7;</code>
     */
    boolean getHistoryAvailable();

    /**
     * <code>bool analysisAvailable = 8;</code>
     */
    boolean getAnalysisAvailable();

    /**
     * <code>repeated bool startGeneration = 9;</code>
     */
    java.util.List<java.lang.Boolean> getStartGenerationList();
    /**
     * <code>repeated bool startGeneration = 9;</code>
     */
    int getStartGenerationCount();
    /**
     * <code>repeated bool startGeneration = 9;</code>
     */
    boolean getStartGeneration(int index);

    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
    java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> 
        getBirthRulesList();
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
        de.gameoflife.payloads.GoFGame.Evaluable getBirthRules(int index);
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
    int getBirthRulesCount();
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
    java.util.List<? extends de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> 
        getBirthRulesOrBuilderList();
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
        de.gameoflife.payloads.GoFGame.EvaluableOrBuilder getBirthRulesOrBuilder(
        int index);

    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
    java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> 
        getDeathRulesList();
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
        de.gameoflife.payloads.GoFGame.Evaluable getDeathRules(int index);
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
    int getDeathRulesCount();
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
    java.util.List<? extends de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> 
        getDeathRulesOrBuilderList();
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
        de.gameoflife.payloads.GoFGame.EvaluableOrBuilder getDeathRulesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Game}
   */
  public  static final class Game extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Game)
      GameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Game.newBuilder() to construct.
    private Game(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Game() {
      gameName_ = "";
      creationDate_ = "";
      lastModifiedDate_ = "";
      userID_ = 0;
      gameID_ = 0;
      borderOverflow_ = false;
      historyAvailable_ = false;
      analysisAvailable_ = false;
      startGeneration_ = java.util.Collections.emptyList();
      birthRules_ = java.util.Collections.emptyList();
      deathRules_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Game(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              gameName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              creationDate_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastModifiedDate_ = s;
              break;
            }
            case 32: {

              userID_ = input.readInt32();
              break;
            }
            case 40: {

              gameID_ = input.readInt32();
              break;
            }
            case 48: {

              borderOverflow_ = input.readBool();
              break;
            }
            case 56: {

              historyAvailable_ = input.readBool();
              break;
            }
            case 64: {

              analysisAvailable_ = input.readBool();
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                startGeneration_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000100;
              }
              startGeneration_.add(input.readBool());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100) && input.getBytesUntilLimit() > 0) {
                startGeneration_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000100;
              }
              while (input.getBytesUntilLimit() > 0) {
                startGeneration_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                birthRules_ = new java.util.ArrayList<de.gameoflife.payloads.GoFGame.Evaluable>();
                mutable_bitField0_ |= 0x00000200;
              }
              birthRules_.add(input.readMessage(de.gameoflife.payloads.GoFGame.Evaluable.parser(), extensionRegistry));
              break;
            }
            case 90: {
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                deathRules_ = new java.util.ArrayList<de.gameoflife.payloads.GoFGame.Evaluable>();
                mutable_bitField0_ |= 0x00000400;
              }
              deathRules_.add(input.readMessage(de.gameoflife.payloads.GoFGame.Evaluable.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          startGeneration_ = java.util.Collections.unmodifiableList(startGeneration_);
        }
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          birthRules_ = java.util.Collections.unmodifiableList(birthRules_);
        }
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          deathRules_ = java.util.Collections.unmodifiableList(deathRules_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.gameoflife.payloads.GoFGame.internal_static_Game_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.gameoflife.payloads.GoFGame.internal_static_Game_fieldAccessorTable
          .ensureFieldAccessorsInitialized(de.gameoflife.payloads.GoFGame.Game.class, de.gameoflife.payloads.GoFGame.Game.Builder.class);
    }

    private int bitField0_;
    public static final int GAMENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object gameName_;
    /**
     * <code>string gameName = 1;</code>
     */
    public java.lang.String getGameName() {
      java.lang.Object ref = gameName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameName_ = s;
        return s;
      }
    }
    /**
     * <code>string gameName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGameNameBytes() {
      java.lang.Object ref = gameName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATIONDATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object creationDate_;
    /**
     * <code>string creationDate = 2;</code>
     */
    public java.lang.String getCreationDate() {
      java.lang.Object ref = creationDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creationDate_ = s;
        return s;
      }
    }
    /**
     * <code>string creationDate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreationDateBytes() {
      java.lang.Object ref = creationDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTMODIFIEDDATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastModifiedDate_;
    /**
     * <code>string lastModifiedDate = 3;</code>
     */
    public java.lang.String getLastModifiedDate() {
      java.lang.Object ref = lastModifiedDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastModifiedDate_ = s;
        return s;
      }
    }
    /**
     * <code>string lastModifiedDate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastModifiedDateBytes() {
      java.lang.Object ref = lastModifiedDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastModifiedDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private int userID_;
    /**
     * <code>int32 userID = 4;</code>
     */
    public int getUserID() {
      return userID_;
    }

    public static final int GAMEID_FIELD_NUMBER = 5;
    private int gameID_;
    /**
     * <code>int32 gameID = 5;</code>
     */
    public int getGameID() {
      return gameID_;
    }

    public static final int BORDEROVERFLOW_FIELD_NUMBER = 6;
    private boolean borderOverflow_;
    /**
     * <code>bool borderOverflow = 6;</code>
     */
    public boolean getBorderOverflow() {
      return borderOverflow_;
    }

    public static final int HISTORYAVAILABLE_FIELD_NUMBER = 7;
    private boolean historyAvailable_;
    /**
     * <code>bool historyAvailable = 7;</code>
     */
    public boolean getHistoryAvailable() {
      return historyAvailable_;
    }

    public static final int ANALYSISAVAILABLE_FIELD_NUMBER = 8;
    private boolean analysisAvailable_;
    /**
     * <code>bool analysisAvailable = 8;</code>
     */
    public boolean getAnalysisAvailable() {
      return analysisAvailable_;
    }

    public static final int STARTGENERATION_FIELD_NUMBER = 9;
    private java.util.List<java.lang.Boolean> startGeneration_;
    /**
     * <code>repeated bool startGeneration = 9;</code>
     */
    public java.util.List<java.lang.Boolean>
        getStartGenerationList() {
      return startGeneration_;
    }
    /**
     * <code>repeated bool startGeneration = 9;</code>
     */
    public int getStartGenerationCount() {
      return startGeneration_.size();
    }
    /**
     * <code>repeated bool startGeneration = 9;</code>
     */
    public boolean getStartGeneration(int index) {
      return startGeneration_.get(index);
    }
    private int startGenerationMemoizedSerializedSize = -1;

    public static final int BIRTHRULES_FIELD_NUMBER = 10;
    private java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> birthRules_;
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
    public java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> getBirthRulesList() {
      return birthRules_;
    }
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
    public java.util.List<? extends de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> 
        getBirthRulesOrBuilderList() {
      return birthRules_;
    }
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
    public int getBirthRulesCount() {
      return birthRules_.size();
    }
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
    public de.gameoflife.payloads.GoFGame.Evaluable getBirthRules(int index) {
      return birthRules_.get(index);
    }
    /**
     * <code>repeated .Evaluable birthRules = 10;</code>
     */
    public de.gameoflife.payloads.GoFGame.EvaluableOrBuilder getBirthRulesOrBuilder(
        int index) {
      return birthRules_.get(index);
    }

    public static final int DEATHRULES_FIELD_NUMBER = 11;
    private java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> deathRules_;
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
    public java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> getDeathRulesList() {
      return deathRules_;
    }
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
    public java.util.List<? extends de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> 
        getDeathRulesOrBuilderList() {
      return deathRules_;
    }
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
    public int getDeathRulesCount() {
      return deathRules_.size();
    }
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
    public de.gameoflife.payloads.GoFGame.Evaluable getDeathRules(int index) {
      return deathRules_.get(index);
    }
    /**
     * <code>repeated .Evaluable deathRules = 11;</code>
     */
    public de.gameoflife.payloads.GoFGame.EvaluableOrBuilder getDeathRulesOrBuilder(
        int index) {
      return deathRules_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getGameNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, gameName_);
      }
      if (!getCreationDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, creationDate_);
      }
      if (!getLastModifiedDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastModifiedDate_);
      }
      if (userID_ != 0) {
        output.writeInt32(4, userID_);
      }
      if (gameID_ != 0) {
        output.writeInt32(5, gameID_);
      }
      if (borderOverflow_ != false) {
        output.writeBool(6, borderOverflow_);
      }
      if (historyAvailable_ != false) {
        output.writeBool(7, historyAvailable_);
      }
      if (analysisAvailable_ != false) {
        output.writeBool(8, analysisAvailable_);
      }
      if (getStartGenerationList().size() > 0) {
        output.writeUInt32NoTag(74);
        output.writeUInt32NoTag(startGenerationMemoizedSerializedSize);
      }
      for (int i = 0; i < startGeneration_.size(); i++) {
        output.writeBoolNoTag(startGeneration_.get(i));
      }
      for (int i = 0; i < birthRules_.size(); i++) {
        output.writeMessage(10, birthRules_.get(i));
      }
      for (int i = 0; i < deathRules_.size(); i++) {
        output.writeMessage(11, deathRules_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGameNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, gameName_);
      }
      if (!getCreationDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, creationDate_);
      }
      if (!getLastModifiedDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastModifiedDate_);
      }
      if (userID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userID_);
      }
      if (gameID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, gameID_);
      }
      if (borderOverflow_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, borderOverflow_);
      }
      if (historyAvailable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, historyAvailable_);
      }
      if (analysisAvailable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, analysisAvailable_);
      }
      {
        int dataSize = 0;
        dataSize = 1 * getStartGenerationList().size();
        size += dataSize;
        if (!getStartGenerationList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        startGenerationMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < birthRules_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, birthRules_.get(i));
      }
      for (int i = 0; i < deathRules_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, deathRules_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.gameoflife.payloads.GoFGame.Game)) {
        return super.equals(obj);
      }
            de.gameoflife.payloads.GoFGame.Game other = (de.gameoflife.payloads.GoFGame.Game) obj;

      boolean result = true;
      result = result && getGameName()
          .equals(other.getGameName());
      result = result && getCreationDate()
          .equals(other.getCreationDate());
      result = result && getLastModifiedDate()
          .equals(other.getLastModifiedDate());
      result = result && (getUserID()
          == other.getUserID());
      result = result && (getGameID()
          == other.getGameID());
      result = result && (getBorderOverflow()
          == other.getBorderOverflow());
      result = result && (getHistoryAvailable()
          == other.getHistoryAvailable());
      result = result && (getAnalysisAvailable()
          == other.getAnalysisAvailable());
      result = result && getStartGenerationList()
          .equals(other.getStartGenerationList());
      result = result && getBirthRulesList()
          .equals(other.getBirthRulesList());
      result = result && getDeathRulesList()
          .equals(other.getDeathRulesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GAMENAME_FIELD_NUMBER;
      hash = (53 * hash) + getGameName().hashCode();
      hash = (37 * hash) + CREATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getCreationDate().hashCode();
      hash = (37 * hash) + LASTMODIFIEDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getLastModifiedDate().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserID();
      hash = (37 * hash) + GAMEID_FIELD_NUMBER;
      hash = (53 * hash) + getGameID();
      hash = (37 * hash) + BORDEROVERFLOW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBorderOverflow());
      hash = (37 * hash) + HISTORYAVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHistoryAvailable());
      hash = (37 * hash) + ANALYSISAVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAnalysisAvailable());
      if (getStartGenerationCount() > 0) {
        hash = (37 * hash) + STARTGENERATION_FIELD_NUMBER;
        hash = (53 * hash) + getStartGenerationList().hashCode();
      }
      if (getBirthRulesCount() > 0) {
        hash = (37 * hash) + BIRTHRULES_FIELD_NUMBER;
        hash = (53 * hash) + getBirthRulesList().hashCode();
      }
      if (getDeathRulesCount() > 0) {
        hash = (37 * hash) + DEATHRULES_FIELD_NUMBER;
        hash = (53 * hash) + getDeathRulesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.gameoflife.payloads.GoFGame.Game parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.gameoflife.payloads.GoFGame.Game parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.gameoflife.payloads.GoFGame.Game prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Game}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Game)
        de.gameoflife.payloads.GoFGame.GameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  de.gameoflife.payloads.GoFGame.internal_static_Game_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  de.gameoflife.payloads.GoFGame.internal_static_Game_fieldAccessorTable
            .ensureFieldAccessorsInitialized(de.gameoflife.payloads.GoFGame.Game.class, de.gameoflife.payloads.GoFGame.Game.Builder.class);
      }

      // Construct using de.gameoflife.payloads.GoFGame.Game.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBirthRulesFieldBuilder();
          getDeathRulesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        gameName_ = "";

        creationDate_ = "";

        lastModifiedDate_ = "";

        userID_ = 0;

        gameID_ = 0;

        borderOverflow_ = false;

        historyAvailable_ = false;

        analysisAvailable_ = false;

        startGeneration_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        if (birthRulesBuilder_ == null) {
          birthRules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          birthRulesBuilder_.clear();
        }
        if (deathRulesBuilder_ == null) {
          deathRules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          deathRulesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  de.gameoflife.payloads.GoFGame.internal_static_Game_descriptor;
      }

      public de.gameoflife.payloads.GoFGame.Game getDefaultInstanceForType() {
        return  de.gameoflife.payloads.GoFGame.Game.getDefaultInstance();
      }

      public de.gameoflife.payloads.GoFGame.Game build() {
                de.gameoflife.payloads.GoFGame.Game result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.gameoflife.payloads.GoFGame.Game buildPartial() {
                de.gameoflife.payloads.GoFGame.Game result = new de.gameoflife.payloads.GoFGame.Game(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.gameName_ = gameName_;
        result.creationDate_ = creationDate_;
        result.lastModifiedDate_ = lastModifiedDate_;
        result.userID_ = userID_;
        result.gameID_ = gameID_;
        result.borderOverflow_ = borderOverflow_;
        result.historyAvailable_ = historyAvailable_;
        result.analysisAvailable_ = analysisAvailable_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          startGeneration_ = java.util.Collections.unmodifiableList(startGeneration_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.startGeneration_ = startGeneration_;
        if (birthRulesBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            birthRules_ = java.util.Collections.unmodifiableList(birthRules_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.birthRules_ = birthRules_;
        } else {
          result.birthRules_ = birthRulesBuilder_.build();
        }
        if (deathRulesBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400)) {
            deathRules_ = java.util.Collections.unmodifiableList(deathRules_);
            bitField0_ = (bitField0_ & ~0x00000400);
          }
          result.deathRules_ = deathRules_;
        } else {
          result.deathRules_ = deathRulesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.gameoflife.payloads.GoFGame.Game) {
          return mergeFrom((de.gameoflife.payloads.GoFGame.Game)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.gameoflife.payloads.GoFGame.Game other) {
        if (other == de.gameoflife.payloads.GoFGame.Game.getDefaultInstance()) return this;
        if (!other.getGameName().isEmpty()) {
          gameName_ = other.gameName_;
          onChanged();
        }
        if (!other.getCreationDate().isEmpty()) {
          creationDate_ = other.creationDate_;
          onChanged();
        }
        if (!other.getLastModifiedDate().isEmpty()) {
          lastModifiedDate_ = other.lastModifiedDate_;
          onChanged();
        }
        if (other.getUserID() != 0) {
          setUserID(other.getUserID());
        }
        if (other.getGameID() != 0) {
          setGameID(other.getGameID());
        }
        if (other.getBorderOverflow() != false) {
          setBorderOverflow(other.getBorderOverflow());
        }
        if (other.getHistoryAvailable() != false) {
          setHistoryAvailable(other.getHistoryAvailable());
        }
        if (other.getAnalysisAvailable() != false) {
          setAnalysisAvailable(other.getAnalysisAvailable());
        }
        if (!other.startGeneration_.isEmpty()) {
          if (startGeneration_.isEmpty()) {
            startGeneration_ = other.startGeneration_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureStartGenerationIsMutable();
            startGeneration_.addAll(other.startGeneration_);
          }
          onChanged();
        }
        if (birthRulesBuilder_ == null) {
          if (!other.birthRules_.isEmpty()) {
            if (birthRules_.isEmpty()) {
              birthRules_ = other.birthRules_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureBirthRulesIsMutable();
              birthRules_.addAll(other.birthRules_);
            }
            onChanged();
          }
        } else {
          if (!other.birthRules_.isEmpty()) {
            if (birthRulesBuilder_.isEmpty()) {
              birthRulesBuilder_.dispose();
              birthRulesBuilder_ = null;
              birthRules_ = other.birthRules_;
              bitField0_ = (bitField0_ & ~0x00000200);
              birthRulesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBirthRulesFieldBuilder() : null;
            } else {
              birthRulesBuilder_.addAllMessages(other.birthRules_);
            }
          }
        }
        if (deathRulesBuilder_ == null) {
          if (!other.deathRules_.isEmpty()) {
            if (deathRules_.isEmpty()) {
              deathRules_ = other.deathRules_;
              bitField0_ = (bitField0_ & ~0x00000400);
            } else {
              ensureDeathRulesIsMutable();
              deathRules_.addAll(other.deathRules_);
            }
            onChanged();
          }
        } else {
          if (!other.deathRules_.isEmpty()) {
            if (deathRulesBuilder_.isEmpty()) {
              deathRulesBuilder_.dispose();
              deathRulesBuilder_ = null;
              deathRules_ = other.deathRules_;
              bitField0_ = (bitField0_ & ~0x00000400);
              deathRulesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDeathRulesFieldBuilder() : null;
            } else {
              deathRulesBuilder_.addAllMessages(other.deathRules_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                de.gameoflife.payloads.GoFGame.Game parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.gameoflife.payloads.GoFGame.Game) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object gameName_ = "";
      /**
       * <code>string gameName = 1;</code>
       */
      public java.lang.String getGameName() {
        java.lang.Object ref = gameName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gameName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gameName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGameNameBytes() {
        java.lang.Object ref = gameName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gameName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gameName = 1;</code>
       */
      public Builder setGameName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gameName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gameName = 1;</code>
       */
      public Builder clearGameName() {
        
        gameName_ = getDefaultInstance().getGameName();
        onChanged();
        return this;
      }
      /**
       * <code>string gameName = 1;</code>
       */
      public Builder setGameNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gameName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object creationDate_ = "";
      /**
       * <code>string creationDate = 2;</code>
       */
      public java.lang.String getCreationDate() {
        java.lang.Object ref = creationDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          creationDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string creationDate = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCreationDateBytes() {
        java.lang.Object ref = creationDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creationDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string creationDate = 2;</code>
       */
      public Builder setCreationDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        creationDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string creationDate = 2;</code>
       */
      public Builder clearCreationDate() {
        
        creationDate_ = getDefaultInstance().getCreationDate();
        onChanged();
        return this;
      }
      /**
       * <code>string creationDate = 2;</code>
       */
      public Builder setCreationDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        creationDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastModifiedDate_ = "";
      /**
       * <code>string lastModifiedDate = 3;</code>
       */
      public java.lang.String getLastModifiedDate() {
        java.lang.Object ref = lastModifiedDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastModifiedDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastModifiedDate = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastModifiedDateBytes() {
        java.lang.Object ref = lastModifiedDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastModifiedDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastModifiedDate = 3;</code>
       */
      public Builder setLastModifiedDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastModifiedDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastModifiedDate = 3;</code>
       */
      public Builder clearLastModifiedDate() {
        
        lastModifiedDate_ = getDefaultInstance().getLastModifiedDate();
        onChanged();
        return this;
      }
      /**
       * <code>string lastModifiedDate = 3;</code>
       */
      public Builder setLastModifiedDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastModifiedDate_ = value;
        onChanged();
        return this;
      }

      private int userID_ ;
      /**
       * <code>int32 userID = 4;</code>
       */
      public int getUserID() {
        return userID_;
      }
      /**
       * <code>int32 userID = 4;</code>
       */
      public Builder setUserID(int value) {
        
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userID = 4;</code>
       */
      public Builder clearUserID() {
        
        userID_ = 0;
        onChanged();
        return this;
      }

      private int gameID_ ;
      /**
       * <code>int32 gameID = 5;</code>
       */
      public int getGameID() {
        return gameID_;
      }
      /**
       * <code>int32 gameID = 5;</code>
       */
      public Builder setGameID(int value) {
        
        gameID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 gameID = 5;</code>
       */
      public Builder clearGameID() {
        
        gameID_ = 0;
        onChanged();
        return this;
      }

      private boolean borderOverflow_ ;
      /**
       * <code>bool borderOverflow = 6;</code>
       */
      public boolean getBorderOverflow() {
        return borderOverflow_;
      }
      /**
       * <code>bool borderOverflow = 6;</code>
       */
      public Builder setBorderOverflow(boolean value) {
        
        borderOverflow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool borderOverflow = 6;</code>
       */
      public Builder clearBorderOverflow() {
        
        borderOverflow_ = false;
        onChanged();
        return this;
      }

      private boolean historyAvailable_ ;
      /**
       * <code>bool historyAvailable = 7;</code>
       */
      public boolean getHistoryAvailable() {
        return historyAvailable_;
      }
      /**
       * <code>bool historyAvailable = 7;</code>
       */
      public Builder setHistoryAvailable(boolean value) {
        
        historyAvailable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool historyAvailable = 7;</code>
       */
      public Builder clearHistoryAvailable() {
        
        historyAvailable_ = false;
        onChanged();
        return this;
      }

      private boolean analysisAvailable_ ;
      /**
       * <code>bool analysisAvailable = 8;</code>
       */
      public boolean getAnalysisAvailable() {
        return analysisAvailable_;
      }
      /**
       * <code>bool analysisAvailable = 8;</code>
       */
      public Builder setAnalysisAvailable(boolean value) {
        
        analysisAvailable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool analysisAvailable = 8;</code>
       */
      public Builder clearAnalysisAvailable() {
        
        analysisAvailable_ = false;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Boolean> startGeneration_ = java.util.Collections.emptyList();
      private void ensureStartGenerationIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          startGeneration_ = new java.util.ArrayList<java.lang.Boolean>(startGeneration_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated bool startGeneration = 9;</code>
       */
      public java.util.List<java.lang.Boolean>
          getStartGenerationList() {
        return java.util.Collections.unmodifiableList(startGeneration_);
      }
      /**
       * <code>repeated bool startGeneration = 9;</code>
       */
      public int getStartGenerationCount() {
        return startGeneration_.size();
      }
      /**
       * <code>repeated bool startGeneration = 9;</code>
       */
      public boolean getStartGeneration(int index) {
        return startGeneration_.get(index);
      }
      /**
       * <code>repeated bool startGeneration = 9;</code>
       */
      public Builder setStartGeneration(
          int index, boolean value) {
        ensureStartGenerationIsMutable();
        startGeneration_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool startGeneration = 9;</code>
       */
      public Builder addStartGeneration(boolean value) {
        ensureStartGenerationIsMutable();
        startGeneration_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool startGeneration = 9;</code>
       */
      public Builder addAllStartGeneration(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureStartGenerationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, startGeneration_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool startGeneration = 9;</code>
       */
      public Builder clearStartGeneration() {
        startGeneration_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }

      private java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> birthRules_ =
        java.util.Collections.emptyList();
      private void ensureBirthRulesIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          birthRules_ = new java.util.ArrayList<de.gameoflife.payloads.GoFGame.Evaluable>(birthRules_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
            de.gameoflife.payloads.GoFGame.Evaluable, de.gameoflife.payloads.GoFGame.Evaluable.Builder, de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> birthRulesBuilder_;

      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> getBirthRulesList() {
        if (birthRulesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(birthRules_);
        } else {
          return birthRulesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public int getBirthRulesCount() {
        if (birthRulesBuilder_ == null) {
          return birthRules_.size();
        } else {
          return birthRulesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public de.gameoflife.payloads.GoFGame.Evaluable getBirthRules(int index) {
        if (birthRulesBuilder_ == null) {
          return birthRules_.get(index);
        } else {
          return birthRulesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder setBirthRules(
          int index, de.gameoflife.payloads.GoFGame.Evaluable value) {
        if (birthRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBirthRulesIsMutable();
          birthRules_.set(index, value);
          onChanged();
        } else {
          birthRulesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder setBirthRules(
          int index, de.gameoflife.payloads.GoFGame.Evaluable.Builder builderForValue) {
        if (birthRulesBuilder_ == null) {
          ensureBirthRulesIsMutable();
          birthRules_.set(index, builderForValue.build());
          onChanged();
        } else {
          birthRulesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder addBirthRules(de.gameoflife.payloads.GoFGame.Evaluable value) {
        if (birthRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBirthRulesIsMutable();
          birthRules_.add(value);
          onChanged();
        } else {
          birthRulesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder addBirthRules(
          int index, de.gameoflife.payloads.GoFGame.Evaluable value) {
        if (birthRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBirthRulesIsMutable();
          birthRules_.add(index, value);
          onChanged();
        } else {
          birthRulesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder addBirthRules(
            de.gameoflife.payloads.GoFGame.Evaluable.Builder builderForValue) {
        if (birthRulesBuilder_ == null) {
          ensureBirthRulesIsMutable();
          birthRules_.add(builderForValue.build());
          onChanged();
        } else {
          birthRulesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder addBirthRules(
          int index, de.gameoflife.payloads.GoFGame.Evaluable.Builder builderForValue) {
        if (birthRulesBuilder_ == null) {
          ensureBirthRulesIsMutable();
          birthRules_.add(index, builderForValue.build());
          onChanged();
        } else {
          birthRulesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder addAllBirthRules(
          java.lang.Iterable<? extends de.gameoflife.payloads.GoFGame.Evaluable> values) {
        if (birthRulesBuilder_ == null) {
          ensureBirthRulesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, birthRules_);
          onChanged();
        } else {
          birthRulesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder clearBirthRules() {
        if (birthRulesBuilder_ == null) {
          birthRules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          birthRulesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public Builder removeBirthRules(int index) {
        if (birthRulesBuilder_ == null) {
          ensureBirthRulesIsMutable();
          birthRules_.remove(index);
          onChanged();
        } else {
          birthRulesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public de.gameoflife.payloads.GoFGame.Evaluable.Builder getBirthRulesBuilder(
          int index) {
        return getBirthRulesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public de.gameoflife.payloads.GoFGame.EvaluableOrBuilder getBirthRulesOrBuilder(
          int index) {
        if (birthRulesBuilder_ == null) {
          return birthRules_.get(index);  } else {
          return birthRulesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public java.util.List<? extends de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> 
           getBirthRulesOrBuilderList() {
        if (birthRulesBuilder_ != null) {
          return birthRulesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(birthRules_);
        }
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public de.gameoflife.payloads.GoFGame.Evaluable.Builder addBirthRulesBuilder() {
        return getBirthRulesFieldBuilder().addBuilder(de.gameoflife.payloads.GoFGame.Evaluable.getDefaultInstance());
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public de.gameoflife.payloads.GoFGame.Evaluable.Builder addBirthRulesBuilder(
          int index) {
        return getBirthRulesFieldBuilder().addBuilder(index, de.gameoflife.payloads.GoFGame.Evaluable.getDefaultInstance());
      }
      /**
       * <code>repeated .Evaluable birthRules = 10;</code>
       */
      public java.util.List<de.gameoflife.payloads.GoFGame.Evaluable.Builder> 
           getBirthRulesBuilderList() {
        return getBirthRulesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
            de.gameoflife.payloads.GoFGame.Evaluable, de.gameoflife.payloads.GoFGame.Evaluable.Builder, de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> 
          getBirthRulesFieldBuilder() {
        if (birthRulesBuilder_ == null) {
          birthRulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                    de.gameoflife.payloads.GoFGame.Evaluable, de.gameoflife.payloads.GoFGame.Evaluable.Builder, de.gameoflife.payloads.GoFGame.EvaluableOrBuilder>(
                  birthRules_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          birthRules_ = null;
        }
        return birthRulesBuilder_;
      }

      private java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> deathRules_ =
        java.util.Collections.emptyList();
      private void ensureDeathRulesIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          deathRules_ = new java.util.ArrayList<de.gameoflife.payloads.GoFGame.Evaluable>(deathRules_);
          bitField0_ |= 0x00000400;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
            de.gameoflife.payloads.GoFGame.Evaluable, de.gameoflife.payloads.GoFGame.Evaluable.Builder, de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> deathRulesBuilder_;

      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public java.util.List<de.gameoflife.payloads.GoFGame.Evaluable> getDeathRulesList() {
        if (deathRulesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(deathRules_);
        } else {
          return deathRulesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public int getDeathRulesCount() {
        if (deathRulesBuilder_ == null) {
          return deathRules_.size();
        } else {
          return deathRulesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public de.gameoflife.payloads.GoFGame.Evaluable getDeathRules(int index) {
        if (deathRulesBuilder_ == null) {
          return deathRules_.get(index);
        } else {
          return deathRulesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder setDeathRules(
          int index, de.gameoflife.payloads.GoFGame.Evaluable value) {
        if (deathRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeathRulesIsMutable();
          deathRules_.set(index, value);
          onChanged();
        } else {
          deathRulesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder setDeathRules(
          int index, de.gameoflife.payloads.GoFGame.Evaluable.Builder builderForValue) {
        if (deathRulesBuilder_ == null) {
          ensureDeathRulesIsMutable();
          deathRules_.set(index, builderForValue.build());
          onChanged();
        } else {
          deathRulesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder addDeathRules(de.gameoflife.payloads.GoFGame.Evaluable value) {
        if (deathRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeathRulesIsMutable();
          deathRules_.add(value);
          onChanged();
        } else {
          deathRulesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder addDeathRules(
          int index, de.gameoflife.payloads.GoFGame.Evaluable value) {
        if (deathRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeathRulesIsMutable();
          deathRules_.add(index, value);
          onChanged();
        } else {
          deathRulesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder addDeathRules(
            de.gameoflife.payloads.GoFGame.Evaluable.Builder builderForValue) {
        if (deathRulesBuilder_ == null) {
          ensureDeathRulesIsMutable();
          deathRules_.add(builderForValue.build());
          onChanged();
        } else {
          deathRulesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder addDeathRules(
          int index, de.gameoflife.payloads.GoFGame.Evaluable.Builder builderForValue) {
        if (deathRulesBuilder_ == null) {
          ensureDeathRulesIsMutable();
          deathRules_.add(index, builderForValue.build());
          onChanged();
        } else {
          deathRulesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder addAllDeathRules(
          java.lang.Iterable<? extends de.gameoflife.payloads.GoFGame.Evaluable> values) {
        if (deathRulesBuilder_ == null) {
          ensureDeathRulesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, deathRules_);
          onChanged();
        } else {
          deathRulesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder clearDeathRules() {
        if (deathRulesBuilder_ == null) {
          deathRules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000400);
          onChanged();
        } else {
          deathRulesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public Builder removeDeathRules(int index) {
        if (deathRulesBuilder_ == null) {
          ensureDeathRulesIsMutable();
          deathRules_.remove(index);
          onChanged();
        } else {
          deathRulesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public de.gameoflife.payloads.GoFGame.Evaluable.Builder getDeathRulesBuilder(
          int index) {
        return getDeathRulesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public de.gameoflife.payloads.GoFGame.EvaluableOrBuilder getDeathRulesOrBuilder(
          int index) {
        if (deathRulesBuilder_ == null) {
          return deathRules_.get(index);  } else {
          return deathRulesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public java.util.List<? extends de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> 
           getDeathRulesOrBuilderList() {
        if (deathRulesBuilder_ != null) {
          return deathRulesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(deathRules_);
        }
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public de.gameoflife.payloads.GoFGame.Evaluable.Builder addDeathRulesBuilder() {
        return getDeathRulesFieldBuilder().addBuilder(de.gameoflife.payloads.GoFGame.Evaluable.getDefaultInstance());
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public de.gameoflife.payloads.GoFGame.Evaluable.Builder addDeathRulesBuilder(
          int index) {
        return getDeathRulesFieldBuilder().addBuilder(index, de.gameoflife.payloads.GoFGame.Evaluable.getDefaultInstance());
      }
      /**
       * <code>repeated .Evaluable deathRules = 11;</code>
       */
      public java.util.List<de.gameoflife.payloads.GoFGame.Evaluable.Builder> 
           getDeathRulesBuilderList() {
        return getDeathRulesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
            de.gameoflife.payloads.GoFGame.Evaluable, de.gameoflife.payloads.GoFGame.Evaluable.Builder, de.gameoflife.payloads.GoFGame.EvaluableOrBuilder> 
          getDeathRulesFieldBuilder() {
        if (deathRulesBuilder_ == null) {
          deathRulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                    de.gameoflife.payloads.GoFGame.Evaluable, de.gameoflife.payloads.GoFGame.Evaluable.Builder, de.gameoflife.payloads.GoFGame.EvaluableOrBuilder>(
                  deathRules_,
                  ((bitField0_ & 0x00000400) == 0x00000400),
                  getParentForChildren(),
                  isClean());
          deathRules_ = null;
        }
        return deathRulesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Game)
    }

    // @@protoc_insertion_point(class_scope:Game)
    private static final de.gameoflife.payloads.GoFGame.Game DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.gameoflife.payloads.GoFGame.Game();
    }

    public static de.gameoflife.payloads.GoFGame.Game getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Game>
        PARSER = new com.google.protobuf.AbstractParser<Game>() {
      public Game parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Game(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Game> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Game> getParserForType() {
      return PARSER;
    }

    public de.gameoflife.payloads.GoFGame.Game getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EvaluableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Evaluable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bool neighbours = 1;</code>
     */
    java.util.List<java.lang.Boolean> getNeighboursList();
    /**
     * <code>repeated bool neighbours = 1;</code>
     */
    int getNeighboursCount();
    /**
     * <code>repeated bool neighbours = 1;</code>
     */
    boolean getNeighbours(int index);
  }
  /**
   * Protobuf type {@code Evaluable}
   */
  public  static final class Evaluable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Evaluable)
      EvaluableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Evaluable.newBuilder() to construct.
    private Evaluable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Evaluable() {
      neighbours_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Evaluable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                neighbours_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000001;
              }
              neighbours_.add(input.readBool());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                neighbours_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                neighbours_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          neighbours_ = java.util.Collections.unmodifiableList(neighbours_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.gameoflife.payloads.GoFGame.internal_static_Evaluable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.gameoflife.payloads.GoFGame.internal_static_Evaluable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(de.gameoflife.payloads.GoFGame.Evaluable.class, de.gameoflife.payloads.GoFGame.Evaluable.Builder.class);
    }

    public static final int NEIGHBOURS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Boolean> neighbours_;
    /**
     * <code>repeated bool neighbours = 1;</code>
     */
    public java.util.List<java.lang.Boolean>
        getNeighboursList() {
      return neighbours_;
    }
    /**
     * <code>repeated bool neighbours = 1;</code>
     */
    public int getNeighboursCount() {
      return neighbours_.size();
    }
    /**
     * <code>repeated bool neighbours = 1;</code>
     */
    public boolean getNeighbours(int index) {
      return neighbours_.get(index);
    }
    private int neighboursMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getNeighboursList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(neighboursMemoizedSerializedSize);
      }
      for (int i = 0; i < neighbours_.size(); i++) {
        output.writeBoolNoTag(neighbours_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 1 * getNeighboursList().size();
        size += dataSize;
        if (!getNeighboursList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        neighboursMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.gameoflife.payloads.GoFGame.Evaluable)) {
        return super.equals(obj);
      }
            de.gameoflife.payloads.GoFGame.Evaluable other = (de.gameoflife.payloads.GoFGame.Evaluable) obj;

      boolean result = true;
      result = result && getNeighboursList()
          .equals(other.getNeighboursList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNeighboursCount() > 0) {
        hash = (37 * hash) + NEIGHBOURS_FIELD_NUMBER;
        hash = (53 * hash) + getNeighboursList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.gameoflife.payloads.GoFGame.Evaluable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.gameoflife.payloads.GoFGame.Evaluable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Evaluable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Evaluable)
        de.gameoflife.payloads.GoFGame.EvaluableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  de.gameoflife.payloads.GoFGame.internal_static_Evaluable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  de.gameoflife.payloads.GoFGame.internal_static_Evaluable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(de.gameoflife.payloads.GoFGame.Evaluable.class, de.gameoflife.payloads.GoFGame.Evaluable.Builder.class);
      }

      // Construct using de.gameoflife.payloads.GoFGame.Evaluable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        neighbours_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  de.gameoflife.payloads.GoFGame.internal_static_Evaluable_descriptor;
      }

      public de.gameoflife.payloads.GoFGame.Evaluable getDefaultInstanceForType() {
        return  de.gameoflife.payloads.GoFGame.Evaluable.getDefaultInstance();
      }

      public de.gameoflife.payloads.GoFGame.Evaluable build() {
                de.gameoflife.payloads.GoFGame.Evaluable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.gameoflife.payloads.GoFGame.Evaluable buildPartial() {
                de.gameoflife.payloads.GoFGame.Evaluable result = new de.gameoflife.payloads.GoFGame.Evaluable(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          neighbours_ = java.util.Collections.unmodifiableList(neighbours_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.neighbours_ = neighbours_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.gameoflife.payloads.GoFGame.Evaluable) {
          return mergeFrom((de.gameoflife.payloads.GoFGame.Evaluable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.gameoflife.payloads.GoFGame.Evaluable other) {
        if (other == de.gameoflife.payloads.GoFGame.Evaluable.getDefaultInstance()) return this;
        if (!other.neighbours_.isEmpty()) {
          if (neighbours_.isEmpty()) {
            neighbours_ = other.neighbours_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNeighboursIsMutable();
            neighbours_.addAll(other.neighbours_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                de.gameoflife.payloads.GoFGame.Evaluable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.gameoflife.payloads.GoFGame.Evaluable) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Boolean> neighbours_ = java.util.Collections.emptyList();
      private void ensureNeighboursIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          neighbours_ = new java.util.ArrayList<java.lang.Boolean>(neighbours_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bool neighbours = 1;</code>
       */
      public java.util.List<java.lang.Boolean>
          getNeighboursList() {
        return java.util.Collections.unmodifiableList(neighbours_);
      }
      /**
       * <code>repeated bool neighbours = 1;</code>
       */
      public int getNeighboursCount() {
        return neighbours_.size();
      }
      /**
       * <code>repeated bool neighbours = 1;</code>
       */
      public boolean getNeighbours(int index) {
        return neighbours_.get(index);
      }
      /**
       * <code>repeated bool neighbours = 1;</code>
       */
      public Builder setNeighbours(
          int index, boolean value) {
        ensureNeighboursIsMutable();
        neighbours_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool neighbours = 1;</code>
       */
      public Builder addNeighbours(boolean value) {
        ensureNeighboursIsMutable();
        neighbours_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool neighbours = 1;</code>
       */
      public Builder addAllNeighbours(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureNeighboursIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, neighbours_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool neighbours = 1;</code>
       */
      public Builder clearNeighbours() {
        neighbours_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Evaluable)
    }

    // @@protoc_insertion_point(class_scope:Evaluable)
    private static final de.gameoflife.payloads.GoFGame.Evaluable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.gameoflife.payloads.GoFGame.Evaluable();
    }

    public static de.gameoflife.payloads.GoFGame.Evaluable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Evaluable>
        PARSER = new com.google.protobuf.AbstractParser<Evaluable>() {
      public Evaluable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Evaluable(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Evaluable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Evaluable> getParserForType() {
      return PARSER;
    }

    public de.gameoflife.payloads.GoFGame.Evaluable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Game_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Game_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Evaluable_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Evaluable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036payloads/schemas/GoFGame.proto\"\216\002\n\004Gam" +
      "e\022\020\n\010gameName\030\001 \001(\t\022\024\n\014creationDate\030\002 \001(" +
      "\t\022\030\n\020lastModifiedDate\030\003 \001(\t\022\016\n\006userID\030\004 " +
      "\001(\005\022\016\n\006gameID\030\005 \001(\005\022\026\n\016borderOverflow\030\006 " +
      "\001(\010\022\030\n\020historyAvailable\030\007 \001(\010\022\031\n\021analysi" +
      "sAvailable\030\010 \001(\010\022\027\n\017startGeneration\030\t \003(" +
      "\010\022\036\n\nbirthRules\030\n \003(\0132\n.Evaluable\022\036\n\ndea" +
      "thRules\030\013 \003(\0132\n.Evaluable\"\037\n\tEvaluable\022\022" +
      "\n\nneighbours\030\001 \003(\010B!\n\026de.gameoflife.payl" +
      "oadsB\007GoFGameb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Game_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Game_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Game_descriptor,
        new java.lang.String[] { "GameName", "CreationDate", "LastModifiedDate", "UserID", "GameID", "BorderOverflow", "HistoryAvailable", "AnalysisAvailable", "StartGeneration", "BirthRules", "DeathRules", });
    internal_static_Evaluable_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Evaluable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Evaluable_descriptor,
        new java.lang.String[] { "Neighbours", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
